version: "3.9"

services:
  camunda:
    container_name: camunda
    image: camunda/camunda-bpm-platform:run-latest
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/engine-rest/engine"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - db
    networks:
      - AMARRADERO

  amarraderollanero:
    container_name: amarraderollanero
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      camunda:
        condition: service_healthy
    networks:
      - AMARRADERO

  db:
    container_name: database
    image: postgres:latest
    # env_file:
    #   - .env  # Cargar las variables de entorno desde el archivo .env
    environment:
      POSTGRES_SERVER: ${DATABASE_SERVER}
      POSTGRES_HOST: ${DATABASE_PORT}
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "9999:5432"
    networks:
      - AMARRADERO

networks:
  AMARRADERO:
    driver: bridge
