version: "3.9"

services:
  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    ports:
      - "8080:8080"
    networks:
      - MSGF
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/engine-rest/engine"]
      interval: 30s
      timeout: 10s
      retries: 5

  msgfoundation:
    build:
      context: .
    ports:
      - "5152:5152"
    depends_on:
      camunda:
        condition: service_healthy
    networks:
      - MSGF

networks:
  MSGF:
