version: "3.9"

services:
  camunda:
    container_name: camunda
    image: camunda/camunda-bpm-platform:run-latest
    ports:
      - "8080:8080"
    networks:
      - MSGF
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/engine-rest/engine"]
      interval: 30s
      timeout: 10s
      retries: 5

  msgfoundation:
    container_name: msgfoundation
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      camunda:
        condition: service_healthy
    networks:
      - MSGF

  db:
    container_name: database
    image: postgres:latest
    # env_file:
    #   - .env  # Cargar las variables de entorno desde el archivo .env
    environment:
      POSTGRES_SERVER: ${DATABASE_SERVER}
      POSTGRES_HOST: ${DATABASE_PORT}
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - MSGF

networks:
  MSGF:
